services:
  usda:
    image: usda
    # build:
    #   context: ./
    #   dockerfile: ./postgres/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usda
      PGHOST: /var/run/postgresql
    volumes:
      - ./out/usda.db:/data/usda.db:ro
      # - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
